### ISSUE TITLE
The window About, is placed in the left corner, and not in the center

### ISSUE THREAD

**Issue by LisaJackson24-2** [Wielding/Windicator#3]
I also noticed such a thing, it is probably not important at all, but still. When clicking on the About item, the window is placed in the left corner, and not in the center, or in the extreme case on the right, where it is actually closer to the icon itself.
I also use the Windicator on a work machine, with an ultra-wide, large 21:9 display with a resolution of 3440x1440. There, at first I didn't even notice where exactly the window opened 😁. Therefore, this nuance is especially noticeable for large screens.

![2023-02-24_12-06](https://user-images.githubusercontent.com/125877645/221153392-5aff4ed7-1703-416f-a4f4-103bd860dbff.png)

**Comment by Wielding** [comment]
Yeah, Windows places it where it thinks best if you don't provide specific coordinates during creation.   I suppose I could get the system metrics for the primary monitor and center it but that would be near the bottom of my priority list since the about box should be rarely accessed.  If it was some other type of dialog (e.g. configuration) I would definitely implement that.  Do you by any chance work in QA?

**Comment by LisaJackson24-2** [comment]
> Yeah, Windows places it where it thinks best if you don't provide specific coordinates during creation. I suppose I could get the system metrics for the primary monitor and center it but that would be near the bottom of my priority list since the about box should be rarely accessed. If it was some other type of dialog (e.g. configuration) I would definitely implement that. Do you by any chance work in QA?

Ok, clearly. Just systematically, the best place for location, Windows for some reason considers the upper left corner 😁

No, my profession is related to design, not QA at all. Just using Ubuntu for a long time leads to writing all kinds of bug reports, feedbacks and issues😂 Now I can't get rid of this habit 😅
